import type { Recipe } from "../models/types";

// Placeholder seed recipes — user will provide their own later
export const SEED_RECIPES: Omit<Recipe, "id" | "createdAt" | "updatedAt">[] = [
	{
		name: "Spaghetti Bolognese",
		description: "Classic Italian meat sauce over pasta",
		servings: 4,
		prepTimeMinutes: 15,
		cookTimeMinutes: 45,
		tags: ["pasta", "italian", "beef"],
		isPreset: true,
		ingredients: [
			{ name: "spaghetti", quantity: 400, unit: "g", displayUnit: "g", category: "dry-goods" },
			{ name: "ground beef", quantity: 500, unit: "g", displayUnit: "g", category: "meat" },
			{ name: "onion", quantity: 1, unit: "unit", category: "produce" },
			{ name: "garlic", quantity: 3, unit: "unit", displayUnit: "clove", category: "produce" },
			{ name: "canned tomatoes", quantity: 400, unit: "g", displayUnit: "g", category: "other" },
			{ name: "tomato paste", quantity: 30, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "olive oil", quantity: 15, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "salt", quantity: 5, unit: "g", displayUnit: "tsp", category: "spice" },
			{ name: "black pepper", quantity: 2, unit: "g", displayUnit: "tsp", category: "spice" },
			{ name: "dried oregano", quantity: 2, unit: "g", displayUnit: "tsp", category: "spice" },
		],
		instructions: [
			"Cook spaghetti according to package directions.",
			"In a large pan, heat olive oil over medium heat. Sauté onion until translucent.",
			"Add garlic, cook 1 minute.",
			"Add ground beef, cook until browned. Drain excess fat.",
			"Stir in canned tomatoes, tomato paste, oregano, salt, and pepper.",
			"Simmer for 30 minutes, stirring occasionally.",
			"Serve sauce over spaghetti.",
		],
	},
	{
		name: "Chicken Stir Fry",
		description: "Quick weeknight stir fry with vegetables",
		servings: 4,
		prepTimeMinutes: 15,
		cookTimeMinutes: 10,
		tags: ["asian", "chicken", "quick"],
		isPreset: true,
		ingredients: [
			{ name: "chicken breast", quantity: 500, unit: "g", displayUnit: "g", category: "meat" },
			{ name: "broccoli", quantity: 200, unit: "g", displayUnit: "g", category: "produce" },
			{ name: "bell pepper", quantity: 2, unit: "unit", category: "produce" },
			{ name: "carrot", quantity: 2, unit: "unit", category: "produce" },
			{ name: "soy sauce", quantity: 45, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "sesame oil", quantity: 15, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "garlic", quantity: 3, unit: "unit", displayUnit: "clove", category: "produce" },
			{ name: "ginger", quantity: 10, unit: "g", displayUnit: "g", category: "produce" },
			{ name: "vegetable oil", quantity: 15, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "rice", quantity: 300, unit: "g", displayUnit: "g", category: "dry-goods" },
		],
		instructions: [
			"Cook rice according to package directions.",
			"Cut chicken into bite-sized pieces. Slice vegetables.",
			"Heat vegetable oil in a wok or large pan over high heat.",
			"Cook chicken until golden, about 5 minutes. Remove and set aside.",
			"Add vegetables to the wok, stir fry 3-4 minutes until crisp-tender.",
			"Return chicken to the wok. Add soy sauce, sesame oil, garlic, and ginger.",
			"Toss everything together for 1 minute. Serve over rice.",
		],
	},
	{
		name: "Meatballs",
		description: "Tender homemade meatballs in tomato sauce",
		servings: 4,
		prepTimeMinutes: 20,
		cookTimeMinutes: 25,
		tags: ["beef", "pork", "comfort"],
		isPreset: true,
		ingredients: [
			{ name: "ground beef", quantity: 250, unit: "g", displayUnit: "g", category: "meat" },
			{ name: "ground pork", quantity: 250, unit: "g", displayUnit: "g", category: "meat" },
			{ name: "breadcrumbs", quantity: 60, unit: "g", displayUnit: "g", category: "dry-goods" },
			{ name: "egg", quantity: 1, unit: "unit", category: "dairy" },
			{ name: "parmesan cheese", quantity: 50, unit: "g", displayUnit: "g", category: "dairy" },
			{ name: "garlic", quantity: 2, unit: "unit", displayUnit: "clove", category: "produce" },
			{ name: "onion", quantity: 1, unit: "unit", category: "produce" },
			{ name: "canned tomatoes", quantity: 400, unit: "g", displayUnit: "g", category: "other" },
			{ name: "olive oil", quantity: 30, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "salt", quantity: 5, unit: "g", displayUnit: "tsp", category: "spice" },
			{ name: "black pepper", quantity: 2, unit: "g", displayUnit: "tsp", category: "spice" },
			{ name: "dried basil", quantity: 2, unit: "g", displayUnit: "tsp", category: "spice" },
		],
		instructions: [
			"Preheat oven to 200°C (400°F).",
			"Mix ground beef, ground pork, breadcrumbs, egg, parmesan, minced garlic, minced onion, salt, pepper, and basil.",
			"Form into golf ball-sized meatballs.",
			"Heat olive oil in an oven-safe pan. Brown meatballs on all sides.",
			"Pour canned tomatoes over meatballs.",
			"Bake for 20 minutes until meatballs are cooked through.",
		],
	},
	{
		name: "Garlic Fried Rice",
		description: "Simple Filipino-style garlic fried rice",
		servings: 2,
		prepTimeMinutes: 5,
		cookTimeMinutes: 10,
		tags: ["filipino", "rice", "quick"],
		isPreset: true,
		ingredients: [
			{ name: "rice", quantity: 400, unit: "g", displayUnit: "g", category: "dry-goods" },
			{ name: "garlic", quantity: 6, unit: "unit", displayUnit: "clove", category: "produce" },
			{ name: "vegetable oil", quantity: 30, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "salt", quantity: 3, unit: "g", displayUnit: "tsp", category: "spice" },
		],
		instructions: [
			"Use day-old cooked rice for best results.",
			"Mince or slice garlic thinly.",
			"Heat oil in a wok over medium heat. Fry garlic until golden and crispy.",
			"Add rice, increase heat to high. Stir fry for 3-5 minutes.",
			"Season with salt. Serve immediately.",
		],
	},
	{
		name: "Pasta with Ground Pork",
		description: "Quick pasta with savory ground pork sauce",
		servings: 4,
		prepTimeMinutes: 10,
		cookTimeMinutes: 20,
		tags: ["pasta", "pork", "quick"],
		isPreset: true,
		ingredients: [
			{ name: "penne", quantity: 400, unit: "g", displayUnit: "g", category: "dry-goods" },
			{ name: "ground pork", quantity: 400, unit: "g", displayUnit: "g", category: "meat" },
			{ name: "onion", quantity: 1, unit: "unit", category: "produce" },
			{ name: "garlic", quantity: 3, unit: "unit", displayUnit: "clove", category: "produce" },
			{ name: "canned tomatoes", quantity: 400, unit: "g", displayUnit: "g", category: "other" },
			{ name: "olive oil", quantity: 15, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "salt", quantity: 5, unit: "g", displayUnit: "tsp", category: "spice" },
			{ name: "black pepper", quantity: 2, unit: "g", displayUnit: "tsp", category: "spice" },
			{ name: "red pepper flakes", quantity: 1, unit: "g", displayUnit: "tsp", category: "spice" },
		],
		instructions: [
			"Cook penne according to package directions.",
			"Heat olive oil, sauté diced onion until soft.",
			"Add garlic, cook 30 seconds.",
			"Add ground pork, cook until browned.",
			"Add canned tomatoes, red pepper flakes, salt, and pepper. Simmer 10 minutes.",
			"Toss with cooked penne.",
		],
	},
	{
		name: "Egg Fried Rice",
		description: "Classic egg fried rice",
		servings: 2,
		prepTimeMinutes: 5,
		cookTimeMinutes: 10,
		tags: ["asian", "rice", "quick", "vegetarian"],
		isPreset: true,
		ingredients: [
			{ name: "rice", quantity: 400, unit: "g", displayUnit: "g", category: "dry-goods" },
			{ name: "egg", quantity: 3, unit: "unit", category: "dairy" },
			{ name: "green onion", quantity: 3, unit: "unit", category: "produce" },
			{ name: "soy sauce", quantity: 30, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "sesame oil", quantity: 5, unit: "ml", displayUnit: "tsp", category: "condiment" },
			{ name: "vegetable oil", quantity: 15, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "salt", quantity: 2, unit: "g", displayUnit: "tsp", category: "spice" },
		],
		instructions: [
			"Use day-old cooked rice.",
			"Beat eggs. Slice green onions.",
			"Heat vegetable oil in a wok over high heat.",
			"Add eggs, scramble quickly, break into small pieces.",
			"Add rice, stir fry 3 minutes on high heat.",
			"Add soy sauce and sesame oil, toss well.",
			"Garnish with green onions.",
		],
	},
	{
		name: "Grilled Chicken Breast",
		description: "Simple marinated grilled chicken",
		servings: 4,
		prepTimeMinutes: 10,
		cookTimeMinutes: 15,
		tags: ["chicken", "healthy", "simple"],
		isPreset: true,
		ingredients: [
			{ name: "chicken breast", quantity: 600, unit: "g", displayUnit: "g", category: "meat" },
			{ name: "olive oil", quantity: 30, unit: "ml", displayUnit: "tbsp", category: "condiment" },
			{ name: "lemon juice", quantity: 30, unit: "ml", displayUnit: "tbsp", category: "produce" },
			{ name: "garlic", quantity: 2, unit: "unit", displayUnit: "clove", category: "produce" },
			{ name: "salt", quantity: 5, unit: "g", displayUnit: "tsp", category: "spice" },
			{ name: "black pepper", quantity: 2, unit: "g", displayUnit: "tsp", category: "spice" },
			{ name: "paprika", quantity: 3, unit: "g", displayUnit: "tsp", category: "spice" },
		],
		instructions: [
			"Mix olive oil, lemon juice, minced garlic, salt, pepper, and paprika.",
			"Marinate chicken for at least 30 minutes.",
			"Grill over medium-high heat, 6-7 minutes per side, until internal temp reaches 74°C (165°F).",
			"Let rest 5 minutes before slicing.",
		],
	},
	{
		name: "Pancakes",
		description: "Fluffy breakfast pancakes",
		servings: 4,
		prepTimeMinutes: 10,
		cookTimeMinutes: 15,
		tags: ["breakfast", "quick"],
		isPreset: true,
		ingredients: [
			{ name: "all-purpose flour", quantity: 250, unit: "g", displayUnit: "g", category: "dry-goods" },
			{ name: "milk", quantity: 300, unit: "ml", displayUnit: "ml", category: "dairy" },
			{ name: "egg", quantity: 2, unit: "unit", category: "dairy" },
			{ name: "butter", quantity: 30, unit: "g", displayUnit: "g", category: "dairy" },
			{ name: "sugar", quantity: 30, unit: "g", displayUnit: "g", category: "dry-goods" },
			{ name: "baking powder", quantity: 10, unit: "g", displayUnit: "tsp", category: "dry-goods" },
			{ name: "salt", quantity: 2, unit: "g", displayUnit: "tsp", category: "spice" },
		],
		instructions: [
			"Mix flour, sugar, baking powder, and salt in a bowl.",
			"In another bowl, whisk milk, eggs, and melted butter.",
			"Pour wet ingredients into dry, stir until just combined (lumps are OK).",
			"Heat a non-stick pan over medium heat. Pour 1/4 cup batter per pancake.",
			"Cook until bubbles form on surface, flip, cook 1-2 more minutes.",
			"Serve with maple syrup, butter, or fresh fruit.",
		],
	},
];
